// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yguhhhyaftdtlyvevpkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndWhoaHlhZnRkdGx5dmV2cGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODg3NjgsImV4cCI6MjA2NjI2NDc2OH0.TUU88ErO_PPjHUOWkc3uAAuaaOTfg5eZdQrCn_BRswk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);